### ISSUE TITLE
Add the latest version of upower-nosystem

### ISSUE THREAD

**Issue by crocket** [arch-openrc/arch-nosystemd#2]
`openrc-eudev/upower-nosystemd 0.9.23-4 (eudev-base)` is too old for xfce4-power-manager.
After replacing upower 0.99.4 with upower-nosystemd 0.9.23, xfce4-power-manager GUI settings do not work.

**Comment by cromerc** [comment]
The openrc-eudev repo is not part of this project.
There are 2 repos [arch-openrc] and [arch-nosystemd] which have all the packages from this project.
[openrc-uedev] is no longer maintained and will have outdated packages. You can find more info here: http://systemd-free.org/news.php
