### ISSUE TITLE
gvfs-udisks2-volume-monitor requires libbluray?

### ISSUE THREAD

**Issue by dan-oconnor** [arch-openrc/arch-nosystemd#4]
gvfs-udisks2-volume-monitor appears to require libbluray.so.1, but it is not a dependency.

attempting to run /usr/lib/gvfs/gvfs-udisks2-volume-monitor fails with the following output:

>/usr/lib/gvfs/gvfs-udisks2-volume-monitor: error while loading shared libraries: libbluray.so.1: cannot open shared object file: No such file or directory

**Comment by dan-oconnor** [comment]
The normal gvfs (as opposed to the nonsystemd version) package ended up working for me, so maybe gvfs-nosystemd isn't need anymore!

**Comment by cromerc** [comment]
gvfs-nosystemd has libbluray as a dependency, which means you should already have libbluray installed if you installed gvfs-nosystemd.

**Comment by archnous** [comment]
@dan-oconnor Perhaps you -Sdd'ed gvfs-nosystemd and got installed without libbluray or libbluray.so.1 was deleted or damaged.

**Comment by archnous** [comment]
BTW, just updated gvfs-nosystemd to 1.32.1.

**Comment by cromerc** [comment]
Packaged and in the repo.

**Comment by dan-oconnor** [comment]
>gvfs-nosystemd has libbluray as a dependency, which means you should already have libbluray installed if you installed gvfs-nosystemd.

Yes, I have libbluray.so.2 and libbluray.so symlink. I do not have libbluray.so.1, though.

I will try updating.
